openapi: 3.0.0
info:
  title: Simple prediction service
  description: API documentation for the simple prediction service.
  version: 1.0.0
paths:
  /predict_proba:
    post:
      summary: Predict probabilities
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                features:
                  type: array
                  items:
                    type: array
                    items:
                      type: number
                  example: [[1.0, 2.0], [3.0, 4.0], [80.0, 2.0]]
      responses:
        '200':
          description: Probabilities for the positive class
          content:
            application/json:
              schema:
                type: object
                properties:
                  probabilities:
                    type: array
                    items:
                      type: number
        '400':
          description: Invalid input
        '500':
          description: Internal server error